version: '3'
services:
   hcp-annotate:
      build: .
      ports:
         - "8888:8888"
      volumes:
         - ${PWD}/.git:/home/jovyan/.extgit
         - ${PWD}/docker/local_cache:/data
      environment:
         - DOCKER_STACKS_JUPYTER_CMD=lab
